### ISSUE TITLE
Ajout de 2 nouvelles valeurs à la table 0203 (Identifier Type)

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/ihe.iti.pam.fr#10]
Dans le contexte du volet de transmission de document(s) CDA en HL7v2 - SEGUR du numérique, Vague 2 du CI_SIS, il est nécessaire d'ajouter deux nouvelles valeurs à la table 0203.
Ces valeurs sont RPPS-Rang et Adeli-Rang.
Cas d'usage : permettre au radiologue d'un cabinet de groupe de transmettre l'identifiant (et le type d'identifiant) de son cabinet au sein du groupe afin de permettre à une plateforme d'intermédiation de générer le VIHF correspondant pour publication d'un document sur le DMP.
Merci d'avance

**Comment by ypoiron** [comment]
Bonjour,

Est-ce que cette demande est toujours d'actualité ?

**Comment by isa-ans** [comment]
hello Yohann,
Non cette demande n'est plus d'actualité. La DNS et la CNAM ont rétropédalé sur le cas d'usage cité.... seul un PS appartenant à l'établissement peut publier sur le DMP en précisant la structure à laquelle il appartient.
