### ISSUE TITLE
Confusion entre OID entre numéro de sécurité social  et INS dans le PID-3

### ISSUE THREAD

**Issue by ChristopherJeanes** [Interop-Sante/ihe.iti.pam.fr#11]
Bonjour,

Nous avons notre GAM qui veut bien arrêter d’envoyer le numéro de sécurité social pour la facturation du séjour dans le PID-19 pour l’envoyer dans le PID-3 comme spécifié dans la norme v2.10.5.  

Par contre, ça veut dire que pour les patients qualifiés, nous recevons maintenant 2 valeurs avec l’OID égal à 1.2.250.1.213.1.4.8 : un avec le CX-5 = INS et l’autre avec CX-5 = NH.

Par exemple, pour un patient qualifié nous recevons dans le PID-3 :
```
170019940100168^^^ASIP-SANTE-INS-NIR&1.2.250.1.213.1.4.8&ISO^INS
170019940100168^^^ASIP-SANTE-NIR&1.2.250.1.213.1.4.8&ISO^NH
```
Pour un patient adulte, les deux valeurs sont les mêmes mais dans le PID-3 nous avons un même OID dans le HD-2 pour deux HD-1 différents (ASIP-SANTE-INS-NIR et ASIP-SANTE-NIR).

Nous avons dit à nos applications récepteurs de se baser sur l’OID dans la compréhension que la correspondance entre valeur et OID était 1:1.  N’est-ce pas le cas ?

Doit-on dire aux applications réceptrices de faire une concaténation entre l’OID et le CX-5 ou bien une concaténation du triplet dans la partie HD?

Merci pour vos idées/réponses.

Cordialement,
Christopher JEANES
DSN du CHU de Toulouse

**Comment by ypoiron** [comment]
Bonjour, 

Désolé de ma réponse tardive ! Effectivement, il est important de bien prendre en compte le CX.5 pour connaître le type de l'identifiant véhiculé, puis ensuite contrôler le HD.1 et le HD.2.

Cordialement,
