### ISSUE TITLE
Consentement du patient

### ISSUE THREAD

**Issue by ypoiron** [Interop-Sante/ihe.iti.pam.fr#12]
Dans le cadre des échanges IHE PAM France et du contexte intra-hospitalier, il est demandé de transmettre le consentement / opposition du patient pour différentes finalités :
* Consentement du patient pour que son identité sorte de l’établissement (à destination d’un serveur de rapprochement d’identité par exemple)
* Consentement si le patient accepte qu’un SMS lui soit envoyé sur son téléphone portable, quelle qu’en soit la raison : confirmation RDV, modification RDV, ...
* Recueil et diffusion du consentement et de la non-opposition du patient respectivement à la consultation (Article L.1111-46 du CSP) et l’alimentation de Mon espace santé (Article L.1111-47 du CSP) en milieu intra-hospitalier. Pour rappel, le patient doit être informé que les membres de son équipe de soins vont alimenter et/ou consulter son DMP et doit avoir la possibilité de s’opposer à l’un ou aux deux pour des raisons différentes. Le recueil de sa réponse doit être différencié pour l’alimentation et la consultation du DMP. Il est demandé de véhiculer 
   * Information et opposition à l’alimentation : N/A (nul) / Informé et opposé / Informé et non opposé
   * Information et opposition à la consultation : N/A (nul) / Informé et opposé / Informé et non opposé

[IHE-CP-ITI-FR-2023-152_Consentement du patient.pdf](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/11903965/IHE-CP-ITI-FR-2023-152_Consentement.du.patient.pdf)

**Comment by Monstermanu** [comment]
Quelques commentaires/questions:

- section 6.14.3 dans le cas d'une limitation (L) comment les systèmes qui reçoivent l'information peuvent avoir le détail de la limitation pour savoir s'ils peuvent permettre l'envoi tel ou tel document ou permettre la consultation?
- section 6.14.4, 6.14.5 et 6.14.6 étant donné que CON-12 et CON-14 ne sont à mentionner que s'ils diffèrent de CON-13, ne faudrait-il pas les rendre conditionnels dans le tableau du segment CON en début de section 16.4? 
- section 6.14.8 le nom du tableau présente une coquille 0496 => 0548
- section 6.14.8 ne faudrait-il pas prendre en compte le cas des représentants légaux n'étant pas parents directs en acceptant la valeur 4 pour les tutelles/curatelles?
- Est-ce qu'il y aurait un intérêt à utiliser CON-23 pour indiquer pourquoi le consentement n'est pas exprimé par le patient? Je ne sais pas s'il y a un intérêt, CON-25 est peut-être suffisant, c'est juste pour être sûr qu'on ne passe pas à côté de quelque chose
- Exemple 1, étant donné la description des CON-12, CON-13 et CON-14, ne faudrait-il pas une CON-13 si CON-12 et CON-14 sont indiqués?
- Exemple 2, peut-on avoir un mode de consentement si on n'a pas d'information sur le consentement? Ca voudrait dire que l'information a été donnée (verbalement dans ce cas) mais que le consentement n'a pas été recueilli?
- Exemple 3, il est indiqué dans la description de CON-12 que ce champs n'est à renseigné que s'il est différent de CON-13 or dans l'exemple, ils ont la même valeur.

**Comment by ypoiron** [comment]
Bonjour, 

Suite aux différents retours, et à la décision prise lors de notre dernière réunion, voici la nouvelle version de la CP concernant la gestion des consentements du patient.

[IHE-CP-ITI-FR-2023-152_Consentement du patient_v2.pdf](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/12855823/IHE-CP-ITI-FR-2023-152_Consentement.du.patient_v2.pdf)

Merci de me faire un retour sur le sujet.

**Comment by jef59** [comment]
Dans les types et modes de consentements, serait-il possible d'ajouter 

Type = DEMAT (envoi des documents par e-mail)
Type = ENQ (enquêtes)
Type = RECH (recherche)
Type = REG (plateforme régionale)

Mode = E (e-consentement)

**Comment by ypoiron** [comment]
Merci @jef59 ! Après il s'agit d'une liste "user defined" donc pas de soucis pour l'augmenter localement. Néanmoins cette liste de valeur me semble cohérente. Par contre e-consentement, à quoi cela correspond (portail de préadmission par exemple) ?

**Comment by jef59** [comment]
Le jeudi 12 octobre 2023 à 19:06:18 UTC+2, Yohann Poiron ***@***.***> a écrit :  
 
 

Merci @jef59 ! Après il s'agit d'une liste "user defined" donc pas de soucis pour l'augmenter localement. Néanmoins cette liste de valeur me semble cohérente. Par contre e-consentement, à quoi cela correspond (portail de préadmission par exemple) ? Oui
Bonne soirée.
JF

**Comment by MARCHAND123** [comment]
Bonjour,
quelques commentaires et questions :
-	je suis d'accord qu'il serait souhaitable d'enrichir les types de consentements pour essayer de couvrir le maximum de besoins, notamment __le consentement du patient pour que son identité sorte de l'établissement (à destination d'une plateforme régionale par exemple)_ qui est évoqué dans l'introduction de la CP mais qui n'est pas repris dans le jeu de valeurs proposé pour alimenter le champ ZCO-2 Type de consentement. La liste de valeurs proposée par @jef59  ci-dessus me convient bien.

- champ ZCO-11 Statut du consentement et jeu de valeurs proposé pour alimenter ce champ :
=> je n'ai pas compris la différence entre la valeur B _le consentement n'a pas été demandé_ et la valeur P _le consentement n'a pas encore été demandé / le consentement n'a pas été donné_
serait-il possible de préciser l'usage de ces 2 valeurs ? Est-ce réellement nécessaire d'avoir les 2, cela ne va-t-il pas entraîner de la confusion si leur usage n'est pas clairement défini ?

- champ ZCO-23 : raison que le consentement n'a pas été exprimé
je n'ai pas compris la signification de la valeur LM _Obligation légale_. Serait-il possible de préciser ? 
Faut-il "relier" cette raison à des valeurs particulières du champ ZCO-11 (statut) (valeur P ou B par exemple)

- question subsidiaire : est-ce que cette gestion du consentement est prévu dans la ressource HL7 Patient FR ? si oui, comment ?

Merci

**Comment by ypoiron** [comment]
Mes retours : 

1. C'est noté pour augmenter la liste des valeurs 
2. Je suis d'accord, j'ai repris la liste internationale. J'ai supprimé le "B"
3. Pour le ZCO-23 je n'ai pas d'exemple précis j'ai repris la liste qui m'a été fournie. 
4. Il s'agit du Patient FHIR ? Si oui, cette notion sera ajoutée par la suite

**Comment by ypoiron** [comment]
Question annexe, la suppression du segment ZFA va-t-elle poser des problématiques pour certains ?

**Comment by DianeBillard** [comment]
Bonjour,

Je n'ai pas eu être présente à la réunion du 18 octobre et donc donner mon point de vive voix.

Qu'englobe le "e-consentement" ? Que les préadmissions ou aussi tous les autres DMN (télésurveillance, téléconsultation, télédiagnostic ... ) ?

Sinon, effectivement, je pense que le segment ZFA n'a plus d'utilité. Et du côté esclave, on mettra en place des lectures des segments ZFA ou ZCO au conditionnel en parallèle selon la version de la PAM.

Je pense aussi qu'il faut paralléliser le travail HL7 v2-PAM avec celle de FHIR Patient. De notre côté tout a un lien car on transcode de l'un à l'autre.

**Comment by ypoiron** [comment]
> Bonjour,
> 
> Je n'ai pas eu être présente à la réunion du 18 octobre et donc donner mon point de vive voix.
> 
> Qu'englobe le "e-consentement" ? Que les préadmissions ou aussi tous les autres DMN (télésurveillance, téléconsultation, télédiagnostic ... ) ? Peut-on aussi ajouter "notification par e-mail" ?
> 
> Sinon, effectivement, je pense que le segment ZFA n'a plus d'utilité. Et du côté esclave, on mettra en place des lectures des segments ZFA ou ZCO au conditionnel en parallèle selon la version de la PAM.
> 
> Je pense aussi qu'il faut paralléliser le travail HL7 v2-PAM avec celle de FHIR Patient. De notre côté tout a un lien car on transcode de l'un à l'autre.

Bonjour Diane, 

Je viens de voir que mon CR n'est jamais parti... Je m'occupe de le rediffuser sur le Google Groups. Néanmoins, il a été acté : 

- Ne pas introduire le segment ZCO 
- Reprendre le segment ZFA 
- Interdire les champs ZFA-6 / 7 / 8
- Ajouter la notion de non-opposition du patient dans le ZFA
