### ISSUE TITLE
Restriction d’accès

### ISSUE THREAD

**Issue by ypoiron** [Interop-Sante/ihe.iti.pam.fr#13]
Être en capacité de gérer une restriction d’accès demandé / requis d'un système à l'autre, à la fois au niveau de la personne / du patient et au niveau de la rencontre / visite.
Exemples:
* Une personne / un patient peut avoir le droit de s'opposer à tout ou partie de ses informations à divulguer. De plus, le patient peut demander que les informations protégées ne soient pas divulguées aux membres de la famille ou aux amis qui peuvent être impliqués dans leurs soins ou à des fins de notification
* Un domaine ou une organisation peut avoir certaines politiques de confidentialité.

[IHE-CP-ITI-FR-2023-153_Restriction_accès.pdf](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/11904044/IHE-CP-ITI-FR-2023-153_Restriction_acces.pdf)

**Comment by Monstermanu** [comment]
Quelques commentaires/questions:

- Section 6.15.2 le nom du tableau présente une coquille HL7 Table 0496 – Consent Type => HL7 table 0717 - Access Restriction Value
- Section 6.15.3 le nom du tableau présente une coquille HL7 Table 0496 – Consent Type => HL7 table 0719 - Access Restriction Reason Code
- Le lien entre ARV et CON quand CON-11 est égal à L est un peu complexe à comprendre, ne serait-il pas judicieux d'avoir un paragraphe expliquant ce cas?

**Comment by ypoiron** [comment]
Merci Manuel pour ce retour. Je m'occupe de corriger les coquilles.

**Comment by ypoiron** [comment]
Voici la version modifiée. 
[IHE-CP-ITI-FR-2023-153_Restriction_accès_v2.pdf](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/12855900/IHE-CP-ITI-FR-2023-153_Restriction_acces_v2.pdf)

**Comment by ypoiron** [comment]
Comme discutée lors de notre dernière réunion, cette CP ne doit pas rentrer dans le cadre de IHE PAM.
