### ISSUE TITLE
CP Transmission représentant légal

### ISSUE THREAD

**Issue by GAQUIERE** [Interop-Sante/ihe.iti.pam.fr#14]
Je propose la CP jointe pour l'ajout d'une valeur sur la table "0131 - Contact Role" qui permettra la transmission de la notion de représentant légal.

[IHE-CP-ITI-FR-2023-XX_RepresentantLegal.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/12299280/IHE-CP-ITI-FR-2023-XX_RepresentantLegal.docx)

**Comment by ypoiron** [comment]
Cette CP sera discutée lors de la prochaine commission de validation. 

[IHE-CP-ITI-FR-2023-154_RepresentantLegal.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/12855949/IHE-CP-ITI-FR-2023-154_RepresentantLegal.docx)

**Comment by ypoiron** [comment]
Cette CP est acceptée et sera disponible dans la version 2.11. 

[IHE-CP-ITI-FR-2023-154_RepresentantLegal.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/13393635/IHE-CP-ITI-FR-2023-154_RepresentantLegal.docx)
