### ISSUE TITLE
Augmentation de la taille du champ EI-1 du type de données EI

### ISSUE THREAD

**Issue by isa-ans** [Interop-Sante/ihe.iti.pam.fr#15]
Un des retours du projectathon 2023 a mis en évidence le fait que la longueur de la 1° composante du type de donnée EI (EI.1) était trop courte en France.
EI (Entity Identifier) permet d'identifier des concepts comme par exemple identifier un document : 1.2.250.1.287.1.1234567.1.16958254718201^Système_X

Actuellement ce champ est limité à 16 caractère dans l'annexe française "Constraints on common HL7 v2.5 data types for ITI Integration Profiles in France":
    "En particulier, la longueur maximum de l’identifiant stocké dans EI-1 est fixée
à 16 caractères pour la France comme pour IHE international"

L’appendix N des annexes du domaine ITI nous permet d’agrandir la taille de ce champ : « IHE constrains the length of the first component to 16 characters. National extensions can extend this length up to a maximum of 199.”

Je propose d'agrandir la longueur de ce champ à 60.
Dans le cadre du SEGUR, ce champ sera obligatoirement agrandi

**Comment by yvarlet** [comment]
Je me demande même s'il ne serait pas préférable de passer à 128 caractères directement.
Suite a la lecture du guide d'intégration 2.9 DMP je constate que celui-ci à réévalué la longueur des OID autorisé en passant de 64 caractères à 128 caractères (page 149-150 du Guide) ce qui impacte les ID de document.

**Comment by ypoiron** [comment]
Nous allons passer cette demande dans la version 1.7 sur les types de données.

**Comment by isa-ans** [comment]
Yohann, peux-tu me préciser à quelle date tu comptes publier la version 1.7? Je la cite dans les volets du SEGUR...

**Comment by ypoiron** [comment]
On a prévu pour la fin de l'année.
