### ISSUE TITLE
Valorisation du MSH-9.3 dans le cas de Z99

### ISSUE THREAD

**Issue by Wifsimster** [Interop-Sante/ihe.iti.pam.fr#17]
Bonjour,

En parcourant le standard 2.10, je ne trouve aucune explication quand à la valorisation du sous-segment `MSH-9.3` dans le cas de message de type `Z99`.

Y a t'il une table de mapping à respecter quand à la valorisation du `MSH-9.3` en fonctionne du message d'origine ?

Ou au contraire tout message `Z99` doit obligatoirement prendre la valeur `ADT^Z99^ADT_01` ?

**Comment by ypoiron** [comment]
Bonjour,

Je confirme que la structure d'un message `Z99` est `ADT_A01`, donc le `MSH.9` doit avoir la structure suivante : `ADT^Z99^ADT_A01`.

Cordialement,
