### ISSUE TITLE
Gestion de la liste des prénoms

### ISSUE THREAD

**Issue by DamienBattistella** [Interop-Sante/ihe.iti.pam.fr#20]
Bonjour,

Nous rencontrons un problème sur la gestion de la liste des prénoms en IHE PAM 2.10.

Nous ne trouvons nul part si cette liste PID-5-3 doit contenir le premier prénom ou non ?

Si nous en croyons les tests du Ségur, cette liste ne contient pas le premier prénom et est donc vide en l'absence de second prénom.

**Comment by ypoiron** [comment]
Bonjour,

Vous avez un élément de réponse dans cette issue : #5 

Effectivement, la documentation n'était pas assez explicite sur le sujet.

Cordialement,

**Comment by DamienBattistella** [comment]
Super merci du retour !
