### ISSUE TITLE
Demande d'une nouvelle classe de venue pour la télésurveillance médicale

### ISSUE THREAD

**Issue by fmacary** [Interop-Sante/ihe.iti.pam.fr#23]
La télésurveillance médicale exercée dans un cadre hospitalier est alimentée par le SIH avec les données administratives des patients (identité, venues). L'activité de télésurveillance pour être facturée par le SIH doit nécessairement s'appuyer sur une venue.
Cette venue de télésurveillance n'entre dans aucune des catégories existantes : hospit, consult, séance, passage aux urgences. En effet, le patient ne vient pas à l'établissement. Il est télésurveillé à distance sur le plan médical.

Le besoin est donc de créer une nouvelle valeur de classe de venue "Télésurveillance médicale" pour renseigner le champ PV1-2 "Patient Class" et son équivalent dans la ressource Encounter de FHIR : **Encounter.class**. La valeur "**VR**" définie en FHIR par le ValueSet https://terminology.hl7.org/5.4.0/ValueSet-encounter-class.html conviendrait à priori.

Le standard HL7 v2 ne connait pas cette valeur, mais la table HL70004 n'est pas contraignante. Donc on peut l'ajouter.

**Comment by ypoiron** [comment]
Voici les modifications apportées :

- Ajout de la valeur "VR" => Télésurveillance médicale dans la table 0004. 

Disponible pour la version 2.11.1.

**Comment by Ben0it-T** [comment]
Bonjour @ypoiron 
La taille (_length_) du champ `PV1-2` est de 1 caractère. Est-il envisageable d'ajouter la valeur "`V`" plutôt que "`VR`" dans la table `0004` ?

**Comment by ypoiron** [comment]
@Ben0it-T C'est exact ! Oui totalement. Merci pour la vigilance
