### ISSUE TITLE
Relecture - Correction de petites coquilles

### ISSUE THREAD

**Issue by Ben0it-T** [Interop-Sante/ihe.iti.pam.fr#24]
Bonjour,
En relisant le document, j'ai trouvé de quelques petites coquilles.

Chapitre 3, Modèle de données minimal commun
Sur la figure, le bloc "Mouvement" fait référence aux données du patient. Il devrait faire référence aux données du mouvement : id du mouvement (ZBE-1), date/heure du mouvement, etc.

Section 6.6, Segment PID
Tableau présentant la structure du segment PID :
- `PID-28` : la cardinalité est vide. Devrait être `[0..0]`.
- `PID-31` : Usage est positionné à `CE`, mais la cardinalité est vide. Est-il possible de mettre la cardinalité sur `[0..1]` pour que Usage et Cardinalité soient cohérents ?
- `PID-38` : la cardinalité est positionnée à `2`. Devrait-être `[0..2]`.

Section 6.9, Segment NK1
Tableau présentant la structure du segment NK1 :
- `NK1-25` : length valorisé à `25080`. Devrait-être valorisé à `250`.
- `NK1-25`, `NK1-28`, `NK1-35` : Usage est valorisé à `O`. Devrait être à `X` _(cf. section 6.3)_

Section 6.13, Segment ZBE
Tableau présentant la structure du segment ZBE :
- `ZBE-3` : La cardinalité est valorisée à `[0..1]`. Devrait-être `[0..0]`.

Section 6.14, Segment ZFA
Tableau présentant la structure du segment ZFA :
- `ZFA-10`, `ZFA-12` : Usage devrait-être `RE` + Cardinalité `[0..1]`

Section 6.14.9 et 6.14.11
- Champ "`ZF1`" => Champ "`ZFA`"

Section 6.16, Segment ZFV
Tableau présentant la structure du segment ZFV :
- `ZFV-8` : Cardinalité valorisée à `[0..N]`. Pour harmoniser, est-il possible de mettre `[0..*]` ?

**Comment by ypoiron** [comment]
Bonjour Benoit, 

Merci pour ce retour. Je m'occupe de corriger les différentes coquilles, et je vais publier une nouvelle version.

**Comment by ypoiron** [comment]
Disponible pour la version 2.11.1.
