### ISSUE TITLE
Clarification sur les segments spécifiques Z

### ISSUE THREAD

**Issue by cmercier-kereval** [Interop-Sante/ihe.iti.pam.fr#25]
Il existe un manque de cohérence entre les parties "'**Insertion des segments spécifiques français**" ITI-30 et ITI-31 (4.2/5.2) et la description de ces segments dans la partie 6.
En particulier les segments **ZFA** et **ZFS** qui sont indiqués comme spécifiques à ITI-31 mais obligatoires pour les événements A28 et A31 d'ITI-30. 

Merci d'avance pour votre attention à cette question et pour tout effort pour améliorer encore la documentation.

**Comment by ypoiron** [comment]
Bonjour,

Merci pour ce retour. Je m'occupe de corriger les différentes coquilles, et je vais publier une nouvelle version.
