### ISSUE TITLE
Transposition du code postal à partir du code INSEE de naissance

### ISSUE THREAD

**Issue by DamienBattistella** [Interop-Sante/ihe.iti.pam.fr#26]
Bonjour,

Lors de la création d'identité, nous rencontrons actuellement un problème avec un serveur de rapprochement tierce.

Dans notre GAM, lors de la création d'identité, il est obligatoire de saisir le code INSEE de naissance mais il n'est pas obligatoire de saisir le code postal de naissance.

Dans l'IHE PAM je ne trouve aucune information pour propager le code INSEE de naissance (qui est la seule information que nous possédons).

Le serveur de rapprochement lui, s'appuie sur le code postal de naissance pour rapprocher l'identité, hors nous ne possédons pas l'information.

Y a t'il une règle existante à appliquer dans ce contexte ? 
Déduire le code postal à partir du code INSEE, en prenant le premier que l'on trouve ?
Forcer le code postal à 99999 quand plusieurs code postaux existe pour un code INSEE ?

**Comment by yvarlet** [comment]
Bonjour , 
La transmission du code COG (INSEE) est décrit dans l'annexe du CI-SIS sur la prise en charge de l'INS dans les standards de l'interopérabilité, voir section 2.4 "Lieu de naissance , Code officiel géographique (COG) de la commune (France) ou du pays
 , Composant 9 (XAD-9) du PID-11, le composant 7 (XAD-7) du PID-11 prenant la 
valeur « BDL »".
https://esante.gouv.fr/sites/default/files/media_entity/documents/ans_cisis-tec_annexe-ins_1.5.pdf

**Comment by ypoiron** [comment]
Bonjour,

Cette information est présente dans l'extension sur les types de données : https://www.interopsante.org/offres/doc_inline_src/412/IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8.pdf 

![Screen 2024-04-05 à 15 28 06](https://github.com/Interop-Sante/ihe.iti.pam.fr/assets/1606018/5e4f2f1c-e694-4f3c-aae2-ed886a88ca80)
