### ISSUE TITLE
Suppression de proches (Next of Kin)

### ISSUE THREAD

**Issue by Ben0it-T** [Interop-Sante/ihe.iti.pam.fr#27]
Bonjour,
La petite question du vendredi à laquelle ne je parviens pas à mettre la main sur la réponse...
Quelles informations devraient être renvoyées message ADT A31 pour notifier une application destinataire qu'un proche a été supprimé ?

Concrètement, supposons qu'un patient possède 3 proches.
- Lors que la suppression du second proche, que doit-on renvoyer dans le HL7 ? Y-a-t-il une règle ?
- Lors de la suppression de l'ensemble des proches, est-il possible de renvoyer un segment NK1 `NK1|""`, pour tout supprimer d'un coup, ou y-a-il une autre façon de faire ?

En vous remerciant

**Comment by ypoiron** [comment]
Bonjour Benoit,

Je confirme que la solution la plus "optimale", c'est d'envoyer des "" sur tous les champs et mettre l'ID du NK1 (NK1.33). Peut-être qu'il sera intéressant de mettre cette notion dans la documentation.

Bonne fin de journée,

**Comment by yvarlet** [comment]
Bonjour ,
J'ai travaillé avec différents éditeurs et dans la majorité des cas la suppression d'une personne de contact se fait simplement par son absence dans le flux, cela fonctionne sur un mode "récapitulatif" (ou annule remplace").
Si on prend votre exemple de messages A31 dans lequel vous n'avez plus que deux personnes dans le second message au lieu de 3, lors de la réception de celui-ci une recherche des contacts rattaché au patient et effectué (en excluant la personne de confiance) et la personne qui ne trouve pas dans le message et "supprimé/desactivé" (compare avec l'id NK1-33) , le fonctionnement est identique avec les transaction ITI-31 et la personne de confiance.
