### ISSUE TITLE
Liste des prénoms : XPN-3

### ISSUE THREAD

**Issue by M-Priour** [Interop-Sante/ihe.iti.pam.fr#28]
Dans l'annexe, il est est indiqué que le champ XPN-3 contient le second prénom et suivants : 
![image](https://github.com/Interop-Sante/ihe.iti.pam.fr/assets/101335975/c488736d-ffef-4a06-987b-d1f7fc14691c)

https://www.interopsante.org/offres/doc_inline_src/412/IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8.pdf

Il faudrait indiquer que le champ contient la liste des prénoms. Ce  champ contient aussi le premier prénom. 
Les exemples dans la spécification sont correctes.

**Comment by ypoiron** [comment]
Bonjour Maël,

Affirmatif, cette issue est en lien avec celle-ci : https://github.com/Interop-Sante/ihe.iti.pam.fr/issues/5 

Je mets @flrt en responsable :)

**Comment by ypoiron** [comment]
Nous allons donc : 

* Indiquer que le XPN-3 contient la liste des prénoms, quel que soit le type. Dans le cas du type D, a priori un seul prénom d'usage, et on positionne ce même prénom d'usage dans la liste des prénoms, donc le XPN-3.
* Corriger les exemples.

Disponible pour la 2.11.2
