### ISSUE TITLE
Erreur de frappe dans le document IHE PAM 2.11 à la page 35

### ISSUE THREAD

**Issue by gonzaguefrete** [Interop-Sante/ihe.iti.pam.fr#29]
Je signale une erreur de frappe dans le document IHE PAM 2.11 à la page 35
=> Il faudrait mettre **bénéficiaire**
 
Page 35 -> Chapitre 6.6.1 PID-3 : Liste des identifiants du patient (CX, répétable)
 
Il est important de ne pas confondre le NIR de facturation avec l’INS-NIR. Le NIR de
facturation permet de faire transiter :
• Numéro de sécurité social de l’ayant droit ou du **bénéfiaire** (patient) : PID.3 avec un
type (CX.5) = NH
• Numéro de sécurité social de l’ouvrant droit (assuré) : IN1.49 avec un type (CX.5) =
SS

**Comment by ypoiron** [comment]
Disponible pour la version 2.11.1.
