### ISSUE TITLE
Erreur de cohérence de valeur CX-5 pour l'INS entre HL7v2 et FHIR

### ISSUE THREAD

**Issue by flrt** [Interop-Sante/ihe.iti.pam.fr#3]
| | |
|-|-|
|Volume|Extension for France of ITI TF-2: Appendix N|
|Version|1.7.3|

# Problème

La valeur du CX-5 définie pour l'INS-NIR est positionnée à `INS`, pour le champ `CX-5` dans le § N.1.

Côté FHIR, Le value Set FHIR [FRCoreValueSetPatientIdentifierType](https://simplifier.net/frenchprofiledfhirar/fr-core-identifier-type-v1-0) définit 

|Code|Display|
|-|-|
|INS-NIA | NIR temporaire|
|INS-NIR | NIR définitif|

# Proposition

Utiliser le même valueset pour hL7v2 et FHIR

**Comment by flrt** [comment]
# Compléments

## Côté FHIR

Le value Set FHIR [FRCoreValueSetPatientIdentifierType](https://simplifier.net/frenchprofiledfhirar/fr-core-identifier-type-v1-0) définit 

|Code|Display|
|-|-|
|INS-NIA | NIR temporaire|
|INS-NIR | NIR définitif

## Coté Gazelle

La valeur du `CX-5` autorisé est `INS`.
Positionner `INS-NIR` conduit à une erreur de validation

|info|valeur|
|-|-|
|Location|ADT_A01/PID[0]/PID-3(Patient Identifier List)[2]/CX-5(identifier type code)|
|Value--- Missing --|INS-NIR|
-Description|Code INS-NIR not found in table HL70203. Possible values are EI, NH, INS-C, INS, NNxxx, PI, PN, RRI, ADELI, RPPS, IDNPS, RI, FINEJ, FINEG, RMESS, RPPS, ADELI, SIREN, SIRET, UF, IDNST, SRV, MR, AN, VN, NDP-
|Type|Table value not found|
|HL7Table|[2.16.840.1.113883.2.8.3.2.1#0203](https://gazelle.ihe.net/GazelleHL7v2Validator/viewResource.seam?oid=2.16.840.1.113883.2.8.3.2.1#0203)|

**Comment by ypoiron** [comment]
Le ValueSet FHIR va être mis à jour pour tenir compte de l'évolution. Il s'agit d'un relicat lié à une non-évolution de FHIR par rapport à IHE PAM France.

**Comment by ypoiron** [comment]
Issue à clôturer dans le nouvel IG de FR Core
