### ISSUE TITLE
Correction sur 2.10 et 2.11 dans la description segment ZFV-2

### ISSUE THREAD

**Issue by PeterBaumgarten** [Interop-Sante/ihe.iti.pam.fr#31]
Bonjour à tous,

En parcourant la description tu ZFV-2, je me suis aperçu d'une coquille sur une référence au PV2-28 alors que la référence semble plutôt porter sur le PV2-38.
Effectivement, il est indiqué dans la capture ci dessous en page 72 de la version 2.10.5 que le ZFV-2 fait référence à la table 0430 disponible en PV2-28 alors que cette table est lié au PV2-38 comme illustrée dans la capture suivante.
      
![image](https://github.com/user-attachments/assets/0ac4e4d9-faa3-4c68-aa51-3e0c9b83344b)

![image](https://github.com/user-attachments/assets/dd58e598-3837-4fda-b353-ae7e5825b99b)

La coquille est également présente dans la dernière version 2.11.
Est-il possible de prévoir une correction à la prochaine session de traitement des CP ?

Bonne journée à tous,

Peter BAUMGARTEN

**Comment by ypoiron** [comment]
Disponible pour la version 2.11.1.
