### ISSUE TITLE
Question : Besoin d'aide pour les codes officiels des pays (issu de la norme ISO 3166) à renseigner par exemple dans le PID-26

### ISSUE THREAD

**Issue by KerJac35** [Interop-Sante/ihe.iti.pam.fr#32]
Bonjour, 

Je me permet de vous contacter concernant une problématique qui nous a été remontée sur le code pays pour le Kosovo (renseigné en tant que pays de naissance et de résidence dans les messages HL7).

Ces codes sont définis dans la table HL7 0399 (https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0399), malheureusement le Kosovo n'est pas mentionné.
Après quelques recherches en ligne, nous avons trouvé deux codes différents sur deux sites différents : 
-	XXK pour le code alphabétique à 3 lettres sur https://codes-pays-iso3166.aliasdmc.fr/codes-pays/iso_3166-1/trois-lettres/kosovo.html
-	XKX pour le code alphabétique à 3 lettres sur https://laendercode.net/fr/country/xk

Sauriez-vous à quelle source officielle se référer ?

Par avance merci pour votre retour. 

Cordialement,

Jérémie AUDIC

**Comment by yvarlet** [comment]
Bonjour,

Concernant la table HL7 0399, celle-ci est alimentée par la norme ISO 3166-1, et le Kosovo n'étant pas présent dans cette norme, vous ne trouverez donc pas de correspondance directe. Son statut en tant que pays indépendant est un sujet complexe, avec une reconnaissance partielle au niveau international. C'est pour cette raison qu'il n'apparaît toujours pas dans la liste officielle des pays.

Concernant les codes comme "XXK", "XK", ou "XKX", il est vrai qu'ils sont parfois utilisés dans certains systèmes pour combler l'absence d'un code officiel pour le Kosovo (OpenStreetMap et banque). Ces codes appartiennent à la catégorie "User-defined" de la norme ISO 3166-1 et ne sont donc pas reconnus comme des codes officiels.

Cependant, si le Kosovo est officiellement reconnu par l'ISO à l'avenir, il est probable qu'il se verra attribuer un code officiel, comme "KS" ou "KO" en ALPHA-2, et "KOS" en ALPHA-3, qui ne sont pas encore attribués ni réservés dans la norme ISO 3166-1. Cela signifie que les codes "XK" ou "XKX" ne seraient plus utilisés. À titre d'exemple, la FIFA et le Comité international olympique reconnaissent le Kosovo avec le code pays ALPHA-3 "KOS".

Si vous utilisez ces codes dans votre système d'information, il est possible qu'ils ne soient pas reconnus par d'autres systèmes.

**Comment by KerJac35** [comment]
Bonjour Yohan, 

Merci beaucoup pour votre aide et votre réponse très claire.

Très bonne journée,
