### ISSUE TITLE
Identification des PS : IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8

### ISSUE THREAD

**Issue by M-Priour** [Interop-Sante/ihe.iti.pam.fr#33]
Dans la spécification "IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8" et dans la table "0203", il est possible d'identifier un PS par : 
- EI
- ADELI
- RPPS
- IDNPS

Dans la section "N.8 XCN : Identifiant composite étendu et nom pour les personnes" (page 28, 29 et 30),  il n'y a plus de mention à IDNPS.  Quand on regarde la structure des exemples, ces derniers sont du type "IDNPS". Les explications font aussi références aussi de manière implicite à la structuration de "IDNPS". 

Afin d'être conforme à l'annexe "Source des données métier pour les professionnels et les structures" et pour lever lever toute ambiguïté, est-ce qu'il ne faudrait pas seulement garder IDNPS dans les choix possibles ?

**Comment by ypoiron** [comment]
Voici les ajouts apportés N.8 XCN : Identifiant composite étendu et nom pour les personnes :

- Ajout de la notion d'identifiant national des PS dans le XCN. Précision sur l'utilisation du IDNPS, RPPS et ADELI. 
- Modification des exemples 

**À terme, nous pourrons supprimer la notion du RPPS, ADELI et de l'identifiant interne établissement pour se baser uniquement sur le IDNPS**. 

Disponible pour la version 2.11.1.
