### ISSUE TITLE
identification des structures : IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8

### ISSUE THREAD

**Issue by M-Priour** [Interop-Sante/ihe.iti.pam.fr#34]
Dans la spécification "IHE_France_Constraints_on_HL7_data_types_for_ITI_V1.8"  et dans la partie "XON : Nom et identifiant pour les organisations" (p 32), est-ce qu'il ne faudrait pas introduire  la notion de "Struct_IdNat" ? 
C'est la manière utiliser identifier les structures par le CI-SIS .
De plus, il ne semble pas possible d'identifier une structure par son RPPS-rang dans la version actuelle.

**Comment by M-Priour** [comment]
# Ajouter une nouvelle valeur 

| XON 1  | XON 6.1 | XON 6.2  | XON 6.3 | XON 7 |XON 8 | XON 9 | XON 10 |
| :------- |:----------| :----------| :--------- |:--------| :-----|:-----|:-----|
| non de la stucture | ?      |1.2.250.1.71.4.2.2  | ISO | Struct_IdNat|x|x|Numero identifiant

## Commentaire
On se retrouve avec  2 type qui ont le même OID (CF ASIPSANTE-ST)

# Modifier le type "ASIPSANTE-ST"

| XON 1  | XON 6.1 | XON 6.2  | XON 6.3 | XON 7 |XON 8 | XON 9 | XON 10 |
| :------- |:----------| :----------| :--------- |:--------| :-----|:-----|:-----|
| non de la stucture | ASIPSANTE-ST     |1.2.250.1.71.4.2.2  | ISO | Struct_IdNat|x|x|Numero identifiant

## Commentaire
Impacts sur les implémentations existantes

**Comment by ypoiron** [comment]
Voici les ajouts apportés N.9	XON : Nom et identifiant pour les organisations :

Ajout de la notion d’identifiant idNat_Struct délivré par une autorité d'enregistrement. 

- Précision sur l'utilisation du idNat_Struct, UF responsabilité médicale, UF responsabilité soins et Etablissement de santé. 
- Modification des exemples

**À terme, nous pourrons supprimer la notion de Finess, Fineg, Finej, SIRET ou SIREN pour se baser uniquement sur le idNat_Struct.**

Disponible pour la version 2.11.1.
