### ISSUE TITLE
Tables ZFA-9 et ZFA-11 identiques 

### ISSUE THREAD

**Issue by cmercier-kereval** [Interop-Sante/ihe.iti.pam.fr#37]
Les tables ZFA-9 et ZFA-11 pour la gestion du consentement portent exactement les mêmes informations.
-> Harmoniser en une seule table utilisée par les 2 champs

**Comment by ypoiron** [comment]
Avec https://github.com/Interop-Sante/ihe.iti.pam.fr/issues/36 cette issue devient caduc. En effet, désormais les 2 tables ont des significations différentes.

Aucune modification apportée par cette issue.
