### ISSUE TITLE
Table IHE-ZFD-4 identique à HL70136

### ISSUE THREAD

**Issue by cmercier-kereval** [Interop-Sante/ihe.iti.pam.fr#38]
La table IHE-ZFD-4 contient un (yes/no). Ce type de code est déjà géré en HL7v2 par la table HL70136.
-> Supprimer la table IHE-ZFD-4 et faire le binding du champ ZFD-4 sur la table HL70136

**Comment by ypoiron** [comment]
Remplacement de la table ZFD-4 en Table HL7 0136.

Disponible pour la version 2.11.1.
