### ISSUE TITLE
Tables du segment ZFS/ZFV

### ISSUE THREAD

**Issue by cmercier-kereval** [Interop-Sante/ihe.iti.pam.fr#39]
Deux anomalies ont été identifiées concernant les tables associées aux segments :

- Les champs ZFS-6 et ZFV-11 sont tous deux liés à une table nommée IHE-3306, mais celle-ci contient des données différentes selon le segment auquel elle est rattachée.

- Les champs ZFS-7 et ZFV-10 pointent vers la même table, qui est nommée 3307 dans le cas du segment ZFS et 3302 pour le segment ZFV.

**Comment by ypoiron** [comment]
Voici les modifications apportées : 

- ZFS-6 : 
- ZFS-7 : 
- ZFV-11 : Modification de le table en **Table IHE France ZFV-11 : Types de prise en charge durant le transport**


Disponible pour la version 2.11.1.
