### ISSUE TITLE
Précision: réference sur XCN-1

### ISSUE THREAD

**Issue by flrt** [Interop-Sante/ihe.iti.pam.fr#4]
| | |
|-|-|
|Volume|Extension for France of ITI TF-2: Appendix N|
|Version|1.7.3|

Dans le paragraphe : XCN-1 : Identifiant de la personne (ST)

Le texte laisse supposer que l'identifiant peut être préfixé selon les règles du GIP CPS, reprisées par le MOS, ou pas.
Sachant que les exemples donnés sont clairs. 

# Proposition

Remplacer

> Par exemple, si le premier chiffre d’un identifiant attribué par le GIP CPS représente un
> typage de cet identifiant, l’identifiant entier, incluant ce premier chiffre sera acheminé dans
> XCN-1, sans que les applications émettrice et réceptrice ne cherchent à interpréter ce premier
> chiffre. En revanche ces applications auront la responsabilité de matérialiser et d’interpréter
> correctement le type de l’identifiant dans XCN-13 (« ADELI » ou « RPPS »).

Par 

> La construction de l’identifiant complet est défini dans le MOS de l’ANS : « Cette identification est obtenue par la concaténation du  type d'identifiant national de personne (provenant de la nomenclature TRE_G08-TypeIdentifiantPersonne) et de l'identifiant de la personne physique provenant, selon le type d’identifiant, soit d’un référentiel national, soit d’un référentiel local propre à la structure d’exercice de la personne physique).
>
> En particulier (liste non exhaustive) :
> - 0 + N° ADELI du professionnel Ex : 0123456789 : identification nationale d’un professionnel identifié par un n° ADELI = 123456789
> - 3 + N° FINESS/identifiant interne du professionnel employé au sein d’une structure FINESS
> - 8 + N° RPPS du professionnel ou de l’étudiant; les étudiants sont dorénavant enregistrés progressivement dans le RPPS
>
> Le premier chiffre de l’identifiant, attribué par le GIP CPS représente un typage de cet identifiant. L’identifiant entier, incluant ce premier chiffre sera acheminé dans XCN-1, pour être homogène avec le MOS, sans que les applications émettrice et réceptrice ne cherchent à interpréter ce premier chiffre. En revanche, ces applications auront la responsabilité de matérialiser et d’interpréter correctement le type de l’identifiant dans XCN-13 (« ADELI » ou « RPPS »).

**Comment by ypoiron** [comment]
Évolution acceptée

**Comment by ypoiron** [comment]
Sera disponible avec la version 1.8 conjointement au profil IHE PAM France 2.11
