### ISSUE TITLE
XPN-3 : tous les prénoms du patient

### ISSUE THREAD

**Issue by flrt** [Interop-Sante/ihe.iti.pam.fr#5]
| | |
|-|-|
|Volume|Extension for France of ITI TF-2: Appendix N|
|Version|1.7.3|

# Problème
  Le titre du paragraphe `XPN-3: Second prénoms et suivants` ne laisse pas supposer que ce champ contient également le 1er prénom comme indiqué dans le texte qui suit le titre, lorsqu'il s'agit de l'appel du téléservice INSi.
  Lorsque les prénoms ne sont pas récupérés du téléservice mais proviennent de la GAM, la description n'est pas aussi explicite.
  
# Proposition
	
Remplacer 
	
> Ce composant contient les prénoms.
>
> Dans le cas d'une identité créée ou modifiée par un appel au téléservice INSi, il s'agit de la liste des prénoms retournée par le téléservice

Par
	
> Ce composant contient tous les prénoms du patient, y compris le premier, que l'on retrouve également dans `XPN-2`.
> Il s'agit de la liste des prénoms du patient, qu'elle soie issue d'une saisie locale ou du retour à l'appel au téléservice INSi.
> Conformément aux spécifications INS, cette liste est constituée des prénoms, séparés par des espaces.

**Comment by ypoiron** [comment]
Ajout de la CP  

[IHE-CP-ITI-FR-2023-149_Prenoms_patient (2).docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/11320762/IHE-CP-ITI-FR-2023-149_Prenoms_patient.2.docx)

**Comment by ypoiron** [comment]
Ajout de la CP 

[IHE-CP-ITI-FR-2023-149_Prenoms_patient.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/11320877/IHE-CP-ITI-FR-2023-149_Prenoms_patient.docx)

**Comment by ChristopherJeanes** [comment]
Bonjour,

Dans le CP après acceptation par le groupe, la correction proposé sur la page 35 du Publication-IHE_FRANCE_PAM_National_Extension_v2.10.5 comporte la liste des prénoms utilisés (XPN-3 lorsque XPN-7 = D).  Ceci est contradictoire avec la correction proposé pour le IHE_France_Constraints_on_HL7_data_types_for_ITI_v.1.7.3 où cette partie est en surbrillance et barrée.  Ca sera confusiogène pour les personnes qui comparent les exemples sur ces 2 publications.
_DE GUERMANTES^MARIANNE^**MARIANNE**^^^^D~DES LAUMES^ORIANNE^ORIANNE^^^^L
Marianne DE GUERMANTES (nom utilisé/prénom utilisé), née Orianne DES LAUMES (nom de naissance)_
Et si on ne mets pas la liste de prénoms dans le XPN-3 lorsque XPN-7 = D, est-ce qu'il est nécessaire d'envoyer les double guillemets lors de la suppression?
_""^""^**""**^^^^D~DES LAUMES^ORIANNE^ORIANNE^^^^L_
Merci.

**Comment by flrt** [comment]
en effet, je ne comprends pas pourquoi on a XPN-3 barré et surligné (ce qui ne correspond à rien en terme d'implémentation).
XPN-3 sera toujours renseigné puisqu'il contient la liste de tous les prénoms.

**Comment by ChristopherJeanes** [comment]
Je comprends effectivement pour le XPN-7 = L, mais pour le XPN-7 = D?  Est-ce que ça correspondrait à la liste des prénoms d'usage?  Je pense que vous aviez la bonne piste en le supprimant de la XPN-3 sur un component Display, mais les exemples dans les 2 documents devrait être correspondants.  Du moins c'est ce que je pense.

**Comment by ypoiron** [comment]
@flrt Peux-tu mettre à jour la CP en conséquence ?

**Comment by ypoiron** [comment]
Nous allons donc : 

* Indiquer que le XPN-3 contient la liste des prénoms, quel que soit le type. Dans le cas du type D, a priori un seul prénom d'usage, et on positionne ce même prénom d'usage dans la liste des prénoms, donc le XPN-3.
* Corriger les exemples.

Disponible pour la 2.11.2
