### ISSUE TITLE
Prise en compte des nouveautés PMSI 2023

### ISSUE THREAD

**Issue by ypoiron** [Interop-Sante/ihe.iti.pam.fr#6]
Dans le cadre des nouveautés PMSI 2023, plusieurs évolutions ou adaptations sont à prendre en compte : 
- une nouvelle variable (inter-champs) est introduite pour indiquer le passage par une structure des urgences. Cet indicateur peut prendre les valeurs suivantes :
   - 5 : passage par une structure des urgences de la même Entité Géographique y compris l'UHCD)
   - U : passage par une structure des urgences d'une autre Entité Géographique (y compris l'UHCD)
   - V : passage par une structure des urgences d'une autre entité géographique et celle de l'entité géographique de l'établissement (UHCD comprises)

- mise à jour de la liste des modes d'entrée PMSI
   - ajout d'une nouvelle valeur O comme mode d'entrée PMSI : patient décédé entré pour prélèvement d'organes
Le contenu de certaines listes doit également être adapté / mis à jour car il n’a pas forcément suivi le réglementaire PMSI des dernières années

[IHE-CP-ITI-FR-2023-150_PMSI 2023.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/11320887/IHE-CP-ITI-FR-2023-150_PMSI.2023.docx)

**Comment by ypoiron** [comment]
Eric va vérifier si on va ajouter un nouveau champ (ZFD.5) ou si on met à jour la table du ZFD.3 avec les 2 autres valeurs.

**Comment by MARCHAND123** [comment]
Bonjour Yohann,
J'avais répondu par mail suite au CR de la réunion du 25/04 que tu nous envoyé.
Je remets ci-dessous l'extrait de ce mail :
"... je confirme qu’il est bien nécessaire d’ajouter un nouveau champ dans le segment ZFM (ZFM-5 Passage par une structure des Urgences).

En effet, il existe des cas où il faut à la fois renseigner le mode de Provenance et l’indicateur de Passage par une structure des Urgences => il n’est pas possible par conséquent de (ré)utiliser le champ ZFM-3 (Mode de Provenance PMSI) pour transmettre l’indicateur de Passage par une structure des Urgences.

Dans le cas où le patient est accueilli aux Urgences dans l’Etablissement A (entité géographique), et qu'il est ensuite transféré vers un service d'hospitalisation MCO dans l’Etablissement B (entité géographique), il faut coder le mouvement d'hospitalisation dans l’Etablissement B comme suit :
•	Mode d'entrée PMSI = 7 (Transfert)  => ZFM-1
•	Mode de provenance PMSI = 1 (Court Séjour)     => ZFM-3
•	Passage par les Urgences PMSI = U (Passage par une structure des Urgences d'une autre EG)   => **ZFM-5** 
"

**Comment by ypoiron** [comment]
Merci Eric,

Cette CP sera discutée lors de la prochaine commission de validation.

**Comment by ypoiron** [comment]
La CP a été acceptée pour la version 2.111

[IHE-CP-ITI-FR-2023-150_PMSI.2023.docx](https://github.com/Interop-Sante/ihe.iti.pam.fr/files/13393596/IHE-CP-ITI-FR-2023-150_PMSI.2023.docx)

**Comment by GAQUIERE** [comment]
Bonjour

Sur le tableau présent pour le champ ZFM-3, on a la valeur 8 qui a été ajoutée avec le libellé "Uniquement pour le mode de **provenance** (ZFM-4)."
Je pense que le libellé devrait plutôt être : "Uniquement pour le mode de **destination** (ZFM-4)."

@MARCHAND123 , @ypoiron ; non ?
