### ISSUE TITLE
Address 2

### ISSUE THREAD

**Issue by ChristianCOUDER** [Interop-Sante/ihe.iti.pam.fr#9]
Bonjour,

Nous voulons faire une modification sur l’utilisation des doubles quotes dans ADRESSE1 et ADRESSE2 (HL7). Notre éditeur n'est pas forcément en adéquation avec ce point et la norme est assez vague à ce sujet.

On souhaite mettre en place les règles suivantes sur l’adresse du patient :

LIGNE1(ADRESSE1)^LIGNE2/S/LIGNE3/S/LIGNE4(ADRESSE2)

Si Ligne1 est vide alors on met le paramétrage double quote ou vide en fonction du paramètre défini dans la table de paramétrage.
Si Ligne2 et ligne 3 et ligne 4 sont vides alors on met le paramétrage double quote ou vide en fonction du paramètre défini dans la table de paramétrage. 

Dans tous les autres cas pour les Ligne2,Ligne3 et Ligne 4 on laisse les valeurs même si par exemple la ligne 3 et 4 sont vides. (pas de double quote)

En résumé, on autorise ce format :  ""^""   mais pas celui-ci ""^""/S/ligne3/S/"" par exemple

Est-ce qu'il est possible de trancher sur ce point ?

bien cordialement,

Christian COUDER

**Comment by ypoiron** [comment]
Bonjour, j'avoue ne pas comprendre réellement le besoin. Un point important à noter : 

1. Un champ VIDE || signifie qu'il n'y a pas de valeur à renseigner (ou que la valeur n'est pas connue)
2. Un champ |""| signifie qu'il y avait **une valeur avant, mais que celle-ci est désormais vidée**

Ex : 

On vient renseigner l'adresse du patient : 
|1 avenue des champs Elysées^2e étage^Paris^^75008^100^H|

On vient supprimer le 2e étage : 
|1 avenue des champs Elysées^""^Paris^^75008^100^H|

On vient supprimer la voie : 
|""^^Paris^^75008^100^H|

Est-ce que cela répond à la question ?

**Comment by ChristianCOUDER** [comment]
Merci pour votre retour, en fait c'est surtout au niveau de la gestion des lignes supplémentaires XAD-2. (LIGNE 2 3 et 4)
Par rapport au contraint 1.7.3 voici l'extrait de la règle règle : 

XAD-2 : Compléments d’adresse (ST)
XAD-2: Other Designation
Ce composant contient le lieu-dit ou une précision géographique comme par exemple le
bâtiment, le numéro d’escalier, l’étage…
Références :
Norme AFNOR XP Z 10-011
RGI : Lieu-dit (identifiant UN00000031)
Pour un émetteur envoyant l’adresse sur plusieurs lignes, XAD-1 correspond à la premiere
ligne ; **XAD-2 peut contenir les autres lignes concaténées et séparées par le code format \S\.** 

que fait-t-on lorsqu'on veut vider la ligne 2 ligne 3 et ligne 4 par exemple et que fait-t-on lorsqu'on veut vider uniquement la ligne 3 et 4.

Bien cordialement,

Christian

**Comment by ypoiron** [comment]
Bonjour,

Après renseignement, votre cas donne : 

|1 avenue des champs Elysées^2e étage/S/Porte 6/S/Ascenceur A^Paris^^75008^100^H|

On vient supprimer l'ascenceur :

|1 avenue des champs Elysées^2e étage/S/Porte 6^Paris^^75008^100^H|

On vient supprimer la porte :

|1 avenue des champs Elysées^2e étage/S/Ascenceur A^Paris^^75008^100^H|


On vient tout supprimer :

|1 avenue des champs Elysées^""^Paris^^75008^100^H|
